server:
  port: 8084

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

logging:
  level:
    com.fedorizvekov.websocket.server.spring: INFO
    org.springframework: INFO