micronaut:
  server:
    port: 8086

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'com.fedorizvekov.http.server.micronaut.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

endpoints:
  stop:
    enabled: true
    sensitive: false