micronaut:
  server:
    port: 8087

  http:
    services:
      host:
        url: http://localhost:8086

request:
  path: /users
  json: "{\"email\": \"client@email.com\", \"firstName\": \"clientFirstName\", \"lastName\": \"clientLastName\"}"

