server:
  port: 8083

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

logging:
  level:
    com.fedorizvekov.http.server.spring: INFO
    org.springframework: INFO
